version: '3.4'
services:

  install:
    build:
      context: ./
      dockerfile: docker/dependencies/Dockerfile
    volumes:
    - ./tmp:/home/app/projects

  test:
    image: lambci/lambda:python3.6
    volumes:
    - ./tmp:/var/task
    command: $LAMBDA_MODULE $TEST_EVENT
    env_file:
    - temp.env
    - aws.env
    - test-lambda.env

  build:
    build:
      context: ./
      dockerfile: docker/deploy/Dockerfile
    volumes:
    - ./tmp:/var/task
    container_name: $LAMBDA_MODULE
    env_file:
    - temp.env
    - aws.env
